name: Harvest Government Events

on:
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:
    # Allow manual triggering
    inputs:
      dry_run:
        description: 'Run in dry-run mode (do not save to database)'
        required: false
        default: 'false'
        type: choice
        options:
          - 'true'
          - 'false'
      verbose:
        description: 'Enable verbose logging'
        required: false
        default: 'true'
        type: choice
        options:
          - 'true'
          - 'false'
      sources:
        description: 'Comma-separated list of sources to harvest (empty for all)'
        required: false
        default: ''
        type: string

jobs:
  harvest:
    name: Harvest Events
    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run harvester
        run: |
          ARGS=""
          
          # Add dry-run flag if requested
          if [[ "${{ github.event.inputs.dry_run }}" == "true" ]]; then
            ARGS="$ARGS --dry-run"
          fi
          
          # Add verbose flag if requested
          if [[ "${{ github.event.inputs.verbose }}" == "true" ]]; then
            ARGS="$ARGS --verbose"
          fi
          
          # Add sources if specified
          if [[ -n "${{ github.event.inputs.sources }}" ]]; then
            ARGS="$ARGS --sources=${{ github.event.inputs.sources }}"
          fi
          
          # Run the harvester with assembled arguments
          npx tsx scripts/harvest-events.ts $ARGS
          
      - name: Save last harvest info
        uses: actions/upload-artifact@v4
        with:
          name: harvest-info
          path: src/data/last-harvest.json
          retention-days: 7